#ifndef ARC_TARGET_SYSCALL_H
#define ARC_TARGET_SYSCALL_H
#define UNAME_MACHINE "arc"
#define UNAME_MINIMUM_RELEASE "2.6.32"
#define TARGET_MCL_CURRENT 1
#define TARGET_MCL_FUTURE  2
#define TARGET_MCL_ONFAULT 4
#define MMAP_SHIFT TARGET_PAGE_BITS

#endif
